{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mr.flutter.plugin.filepicker",
    "module": "file_picker_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-9aa7816315095c86410527932918c718cb35e7d6"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_release-1.0.aar",
          "url": "file_picker_release-1.0.aar",
          "size": 27406,
          "sha512": "ffbf18a11e709054bf3ab99db23e6f3def1671bad12b224cfcb75d49eb2a1cc0f43789398c08c0399e4045a09859cca4e23393b16e8959f77a52651f188b1131",
          "sha256": "8758b9df7024570312e8213d362bb992ff614bbc823c67c13497450a7a24245a",
          "sha1": "28982c1a4cb7a7ab027f5692304684e74d919335",
          "md5": "2fa7cc898ecd178d3517198d30dc9ff3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-9aa7816315095c86410527932918c718cb35e7d6"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_release-1.0.aar",
          "url": "file_picker_release-1.0.aar",
          "size": 27406,
          "sha512": "ffbf18a11e709054bf3ab99db23e6f3def1671bad12b224cfcb75d49eb2a1cc0f43789398c08c0399e4045a09859cca4e23393b16e8959f77a52651f188b1131",
          "sha256": "8758b9df7024570312e8213d362bb992ff614bbc823c67c13497450a7a24245a",
          "sha1": "28982c1a4cb7a7ab027f5692304684e74d919335",
          "md5": "2fa7cc898ecd178d3517198d30dc9ff3"
        }
      ]
    }
  ]
}
