{
  "formatVersion": "1.1",
  "component": {
    "group": "blip.sdk.chat",
    "module": "flutter",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.mr.flutter.plugin.filepicker",
          "module": "file_picker",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.just_audio",
          "module": "just_audio",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.crazecoder.openfile",
          "module": "open_filex",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.jrai.flutter_keyboard_visibility",
          "module": "flutter_keyboard_visibility",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.0-debug.aar",
          "url": "flutter-1.0-debug.aar",
          "size": 19057604,
          "sha512": "f68c20ffc40d11ddaf1d0c11fad3cf798c5fae1315d9890e1f85f0e9fe38069bce58892468708570e577ea5275458dcbcd04ca932581e869fba40cd7c801dfa9",
          "sha256": "b05639b86de1f7f608c583a27a752eb9210b80f62036b757772e624b74c04bad",
          "sha1": "e3189ed585a11d28c829b67fdf14625dfae8cd18",
          "md5": "fc07cd25da4dac93a0c393515db7dc79"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.mr.flutter.plugin.filepicker",
          "module": "file_picker",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.just_audio",
          "module": "just_audio",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.crazecoder.openfile",
          "module": "open_filex",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.jrai.flutter_keyboard_visibility",
          "module": "flutter_keyboard_visibility",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.0-debug.aar",
          "url": "flutter-1.0-debug.aar",
          "size": 19057604,
          "sha512": "f68c20ffc40d11ddaf1d0c11fad3cf798c5fae1315d9890e1f85f0e9fe38069bce58892468708570e577ea5275458dcbcd04ca932581e869fba40cd7c801dfa9",
          "sha256": "b05639b86de1f7f608c583a27a752eb9210b80f62036b757772e624b74c04bad",
          "sha1": "e3189ed585a11d28c829b67fdf14625dfae8cd18",
          "md5": "fc07cd25da4dac93a0c393515db7dc79"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.mr.flutter.plugin.filepicker",
          "module": "file_picker",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.just_audio",
          "module": "just_audio",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.crazecoder.openfile",
          "module": "open_filex",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.jrai.flutter_keyboard_visibility",
          "module": "flutter_keyboard_visibility",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.0-release.aar",
          "url": "flutter-1.0-release.aar",
          "size": 10450375,
          "sha512": "a2cdc745053ecfd210029c24a485bc0b4b50267fa595a1ce85756b0a762076ed9c415738bdb487c9763b729b1e649eb0fa95fa43ec7a54ccd1a71a21ea2a43d5",
          "sha256": "88ebf5dc0e887ac1848fd297c678f436bb123fb16960736d20673da7e79c411a",
          "sha1": "d8d83f0790c2996712e24a879ec0b9a8e17f1dc9",
          "md5": "2148dac7dc180e631935209f3e621b7d"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.mr.flutter.plugin.filepicker",
          "module": "file_picker",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.just_audio",
          "module": "just_audio",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.crazecoder.openfile",
          "module": "open_filex",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.jrai.flutter_keyboard_visibility",
          "module": "flutter_keyboard_visibility",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.0-release.aar",
          "url": "flutter-1.0-release.aar",
          "size": 10450375,
          "sha512": "a2cdc745053ecfd210029c24a485bc0b4b50267fa595a1ce85756b0a762076ed9c415738bdb487c9763b729b1e649eb0fa95fa43ec7a54ccd1a71a21ea2a43d5",
          "sha256": "88ebf5dc0e887ac1848fd297c678f436bb123fb16960736d20673da7e79c411a",
          "sha1": "d8d83f0790c2996712e24a879ec0b9a8e17f1dc9",
          "md5": "2148dac7dc180e631935209f3e621b7d"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.mr.flutter.plugin.filepicker",
          "module": "file_picker",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.just_audio",
          "module": "just_audio",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.crazecoder.openfile",
          "module": "open_filex",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.jrai.flutter_keyboard_visibility",
          "module": "flutter_keyboard_visibility",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.0-profile.aar",
          "url": "flutter-1.0-profile.aar",
          "size": 398718,
          "sha512": "869c0454f63762121ddd9012db5fb2900370a71f44eb537cb856ad2963bc775e8e8a39697e956db83e135a1d792c5f505894bd2eb8237e1fda1de96d1aa09607",
          "sha256": "ef5b4fd304b7e94a3192c409df57dabb43fe0e0d2706abbbe148e142bdc5df90",
          "sha1": "618240f74285235139c48c43c714b576a3992271",
          "md5": "6821a033fb425d61a786f7bea8fe7631"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.mr.flutter.plugin.filepicker",
          "module": "file_picker",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.just_audio",
          "module": "just_audio",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.crazecoder.openfile",
          "module": "open_filex",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.jrai.flutter_keyboard_visibility",
          "module": "flutter_keyboard_visibility",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter-1.0-profile.aar",
          "url": "flutter-1.0-profile.aar",
          "size": 398718,
          "sha512": "869c0454f63762121ddd9012db5fb2900370a71f44eb537cb856ad2963bc775e8e8a39697e956db83e135a1d792c5f505894bd2eb8237e1fda1de96d1aa09607",
          "sha256": "ef5b4fd304b7e94a3192c409df57dabb43fe0e0d2706abbbe148e142bdc5df90",
          "sha1": "618240f74285235139c48c43c714b576a3992271",
          "md5": "6821a033fb425d61a786f7bea8fe7631"
        }
      ]
    }
  ]
}
