{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jrai.flutter_keyboard_visibility",
    "module": "flutter_keyboard_visibility_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-9aa7816315095c86410527932918c718cb35e7d6"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_keyboard_visibility_debug-1.0.aar",
          "url": "flutter_keyboard_visibility_debug-1.0.aar",
          "size": 5055,
          "sha512": "3f711d7484394bd35804f4a9eebb828e5e7cf03dfc62a6752241b70131a9a79f0707e0194cba54652a68c1d0e47c965a0e29adba8884c93ff3ef9417aaced38b",
          "sha256": "6599c86efd97934e664ffb48010f810d95a6aa0101a4ccb43c7de9f2906aae3a",
          "sha1": "ceacb73190a69bb558467ce9edc51785ca827bf8",
          "md5": "8324d24960e93c71ce16e5d9f9e27436"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-9aa7816315095c86410527932918c718cb35e7d6"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_keyboard_visibility_debug-1.0.aar",
          "url": "flutter_keyboard_visibility_debug-1.0.aar",
          "size": 5055,
          "sha512": "3f711d7484394bd35804f4a9eebb828e5e7cf03dfc62a6752241b70131a9a79f0707e0194cba54652a68c1d0e47c965a0e29adba8884c93ff3ef9417aaced38b",
          "sha256": "6599c86efd97934e664ffb48010f810d95a6aa0101a4ccb43c7de9f2906aae3a",
          "sha1": "ceacb73190a69bb558467ce9edc51785ca827bf8",
          "md5": "8324d24960e93c71ce16e5d9f9e27436"
        }
      ]
    }
  ]
}
