{
  "formatVersion": "1.1",
  "component": {
    "group": "com.crazecoder.openfile",
    "module": "open_filex_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-9aa7816315095c86410527932918c718cb35e7d6"
          }
        }
      ],
      "files": [
        {
          "name": "open_filex_profile-1.0.aar",
          "url": "open_filex_profile-1.0.aar",
          "size": 13626,
          "sha512": "dee1b0bef518a561b182f90170a5aeffd06afddcfaaf232ae5c83551ce03e78753b41c725ab30cf75b754a4722e8268280b0af1d8ba0fa0d7deba75d72d1c815",
          "sha256": "aa18faa9111365b6cfd9ad66293ceb9d241597344c41f6c984a1fb920a7006cd",
          "sha1": "b680521189c83163649ccf667cef2bbbcde59780",
          "md5": "4df53b6d3a128c49ae548aac2116e410"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-9aa7816315095c86410527932918c718cb35e7d6"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "open_filex_profile-1.0.aar",
          "url": "open_filex_profile-1.0.aar",
          "size": 13626,
          "sha512": "dee1b0bef518a561b182f90170a5aeffd06afddcfaaf232ae5c83551ce03e78753b41c725ab30cf75b754a4722e8268280b0af1d8ba0fa0d7deba75d72d1c815",
          "sha256": "aa18faa9111365b6cfd9ad66293ceb9d241597344c41f6c984a1fb920a7006cd",
          "sha1": "b680521189c83163649ccf667cef2bbbcde59780",
          "md5": "4df53b6d3a128c49ae548aac2116e410"
        }
      ]
    }
  ]
}
