{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mr.flutter.plugin.filepicker",
    "module": "file_picker_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_profile-1.0.aar",
          "url": "file_picker_profile-1.0.aar",
          "size": 27147,
          "sha512": "fff7f80f6c3a8046f7a1b0ff1c01782a7612bc0b9fc729b211bc4269e49112e48f51caef79241c77270c426dcb9fd6f8a8db1fe39adb7b149e82267d38324804",
          "sha256": "f4511ddc80d89cbb025efe279dd6f0c4a2c2383f195ad564c1d24b30de4d9d77",
          "sha1": "177b2dc2c64d9ff9906b135e3712bee956d24686",
          "md5": "69ce21ea39cc1af03dec4c83992a0759"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_profile-1.0.aar",
          "url": "file_picker_profile-1.0.aar",
          "size": 27147,
          "sha512": "fff7f80f6c3a8046f7a1b0ff1c01782a7612bc0b9fc729b211bc4269e49112e48f51caef79241c77270c426dcb9fd6f8a8db1fe39adb7b149e82267d38324804",
          "sha256": "f4511ddc80d89cbb025efe279dd6f0c4a2c2383f195ad564c1d24b30de4d9d77",
          "sha1": "177b2dc2c64d9ff9906b135e3712bee956d24686",
          "md5": "69ce21ea39cc1af03dec4c83992a0759"
        }
      ]
    }
  ]
}
