{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mr.flutter.plugin.filepicker",
    "module": "file_picker_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-9aa7816315095c86410527932918c718cb35e7d6"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_profile-1.0.aar",
          "url": "file_picker_profile-1.0.aar",
          "size": 27407,
          "sha512": "2d902b02c671e41cc7b431f33e319d1a9b84e2f2ced2c5582fd8857f0692324d377cac5f80342a681c8f5da6d315dd9f0e24faca116b5a110b3c5cc52e95f262",
          "sha256": "18b5ce87ecb089789f46c3560ccdbd8b44c4d9d0a1dbedcad5aaa849f0d73589",
          "sha1": "265cd2a878c12d8c3c7ef8d3ca84830fbf8a65b0",
          "md5": "d487a7038bc3863342f0ad427b612dcd"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-9aa7816315095c86410527932918c718cb35e7d6"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_profile-1.0.aar",
          "url": "file_picker_profile-1.0.aar",
          "size": 27407,
          "sha512": "2d902b02c671e41cc7b431f33e319d1a9b84e2f2ced2c5582fd8857f0692324d377cac5f80342a681c8f5da6d315dd9f0e24faca116b5a110b3c5cc52e95f262",
          "sha256": "18b5ce87ecb089789f46c3560ccdbd8b44c4d9d0a1dbedcad5aaa849f0d73589",
          "sha1": "265cd2a878c12d8c3c7ef8d3ca84830fbf8a65b0",
          "md5": "d487a7038bc3863342f0ad427b612dcd"
        }
      ]
    }
  ]
}
