{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mr.flutter.plugin.filepicker",
    "module": "file_picker_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-9aa7816315095c86410527932918c718cb35e7d6"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_debug-1.0.aar",
          "url": "file_picker_debug-1.0.aar",
          "size": 28602,
          "sha512": "b17cc8317f83c87def7870e998f791bf42381acee66d9ba386ccf95342143a300e1dee679b732ac0256ca238a00cf2f1d7d84966fd7c4df5af604344be9e7621",
          "sha256": "df0ee0eb808b2855a75f537b2e6fced0f275ab789b0769da65df160dfe374b43",
          "sha1": "d647895729e72e67bc577285432932ce177ce64e",
          "md5": "69a2772b54660e358f3dc75ac10e5aa2"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-9aa7816315095c86410527932918c718cb35e7d6"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_debug-1.0.aar",
          "url": "file_picker_debug-1.0.aar",
          "size": 28602,
          "sha512": "b17cc8317f83c87def7870e998f791bf42381acee66d9ba386ccf95342143a300e1dee679b732ac0256ca238a00cf2f1d7d84966fd7c4df5af604344be9e7621",
          "sha256": "df0ee0eb808b2855a75f537b2e6fced0f275ab789b0769da65df160dfe374b43",
          "sha1": "d647895729e72e67bc577285432932ce177ce64e",
          "md5": "69a2772b54660e358f3dc75ac10e5aa2"
        }
      ]
    }
  ]
}
