{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mr.flutter.plugin.filepicker",
    "module": "file_picker",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker-1.0-debug.aar",
          "url": "file_picker-1.0-debug.aar",
          "size": 28315,
          "sha512": "b092e6efa1c92dec441be8f6bff2eadd00ba2add1abdd054aec972f151b39dd69c65d859ce3fa8e1eb716b3d0523c35330fee668555408519b4fdddf93fdcac4",
          "sha256": "b3fea89406eb19df0e12910ab583b1fe4bf2e74097c2d85b616ce9e64fbb942e",
          "sha1": "946abc7dd8513d8caf36e438ee8c150426d55c03",
          "md5": "9d6ec2d12be2d5b8f7e48f35e1916973"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker-1.0-debug.aar",
          "url": "file_picker-1.0-debug.aar",
          "size": 28315,
          "sha512": "b092e6efa1c92dec441be8f6bff2eadd00ba2add1abdd054aec972f151b39dd69c65d859ce3fa8e1eb716b3d0523c35330fee668555408519b4fdddf93fdcac4",
          "sha256": "b3fea89406eb19df0e12910ab583b1fe4bf2e74097c2d85b616ce9e64fbb942e",
          "sha1": "946abc7dd8513d8caf36e438ee8c150426d55c03",
          "md5": "9d6ec2d12be2d5b8f7e48f35e1916973"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker-1.0-release.aar",
          "url": "file_picker-1.0-release.aar",
          "size": 27145,
          "sha512": "c89150a559a48966e1dd4985e011b6c8221e09976ed1ccae7cf388efdf1fcea6201a722d7cf5bbb380901f6b013f1d3da9d714a7143f601368c5347f9e9d552b",
          "sha256": "8856e16b257f98e2f1b9879966a4f4e1becb21a3ca5ee38ae62aadbf8f06dcc0",
          "sha1": "d7245264171757b97d5a2a2384fdaa3fddf5a69f",
          "md5": "7e6acdf0925664c6c23686f5e7b15ca2"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker-1.0-release.aar",
          "url": "file_picker-1.0-release.aar",
          "size": 27145,
          "sha512": "c89150a559a48966e1dd4985e011b6c8221e09976ed1ccae7cf388efdf1fcea6201a722d7cf5bbb380901f6b013f1d3da9d714a7143f601368c5347f9e9d552b",
          "sha256": "8856e16b257f98e2f1b9879966a4f4e1becb21a3ca5ee38ae62aadbf8f06dcc0",
          "sha1": "d7245264171757b97d5a2a2384fdaa3fddf5a69f",
          "md5": "7e6acdf0925664c6c23686f5e7b15ca2"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker-1.0-profile.aar",
          "url": "file_picker-1.0-profile.aar",
          "size": 27147,
          "sha512": "fff7f80f6c3a8046f7a1b0ff1c01782a7612bc0b9fc729b211bc4269e49112e48f51caef79241c77270c426dcb9fd6f8a8db1fe39adb7b149e82267d38324804",
          "sha256": "f4511ddc80d89cbb025efe279dd6f0c4a2c2383f195ad564c1d24b30de4d9d77",
          "sha1": "177b2dc2c64d9ff9906b135e3712bee956d24686",
          "md5": "69ce21ea39cc1af03dec4c83992a0759"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker-1.0-profile.aar",
          "url": "file_picker-1.0-profile.aar",
          "size": 27147,
          "sha512": "fff7f80f6c3a8046f7a1b0ff1c01782a7612bc0b9fc729b211bc4269e49112e48f51caef79241c77270c426dcb9fd6f8a8db1fe39adb7b149e82267d38324804",
          "sha256": "f4511ddc80d89cbb025efe279dd6f0c4a2c2383f195ad564c1d24b30de4d9d77",
          "sha1": "177b2dc2c64d9ff9906b135e3712bee956d24686",
          "md5": "69ce21ea39cc1af03dec4c83992a0759"
        }
      ]
    }
  ]
}
