{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-9aa7816315095c86410527932918c718cb35e7d6"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_release-1.0.aar",
          "url": "sqflite_release-1.0.aar",
          "size": 44669,
          "sha512": "860f555e5ef167c8767e82b3885c6c66787cc8d6d68f1a06dd79620beab045d7196fee860091927504b1b55cb3de56ee566f3849b0dfc94a2c42cb3e0956a163",
          "sha256": "9d2b729fd8f10a01adc17768e27dbd9b8226ed6bdccb2a6385e176c26713bd39",
          "sha1": "3ae4f68c74d7ce1e20d339a25e8fb590210775df",
          "md5": "173ede5cf925ef08a5367d46277cb17f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-9aa7816315095c86410527932918c718cb35e7d6"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_release-1.0.aar",
          "url": "sqflite_release-1.0.aar",
          "size": 44669,
          "sha512": "860f555e5ef167c8767e82b3885c6c66787cc8d6d68f1a06dd79620beab045d7196fee860091927504b1b55cb3de56ee566f3849b0dfc94a2c42cb3e0956a163",
          "sha256": "9d2b729fd8f10a01adc17768e27dbd9b8226ed6bdccb2a6385e176c26713bd39",
          "sha1": "3ae4f68c74d7ce1e20d339a25e8fb590210775df",
          "md5": "173ede5cf925ef08a5367d46277cb17f"
        }
      ]
    }
  ]
}
