{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-9aa7816315095c86410527932918c718cb35e7d6"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_profile-1.0.aar",
          "url": "sqflite_profile-1.0.aar",
          "size": 44670,
          "sha512": "1c0970ade254f78350fdb1ea382e34021da95ce4b4b228eafa8a37452168858fa66a975228d835422a104ca62a6c4edabb5d820e562a89a855e0c4534908c051",
          "sha256": "682a5a849cc3000aabf9c907f524316fedcb8266d6a7cd2d978e969cc853da65",
          "sha1": "a00756c879e25cc5522a545a0fc86f3407311489",
          "md5": "56d07c46943c0721f406cd321bd398d6"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-9aa7816315095c86410527932918c718cb35e7d6"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_profile-1.0.aar",
          "url": "sqflite_profile-1.0.aar",
          "size": 44670,
          "sha512": "1c0970ade254f78350fdb1ea382e34021da95ce4b4b228eafa8a37452168858fa66a975228d835422a104ca62a6c4edabb5d820e562a89a855e0c4534908c051",
          "sha256": "682a5a849cc3000aabf9c907f524316fedcb8266d6a7cd2d978e969cc853da65",
          "sha1": "a00756c879e25cc5522a545a0fc86f3407311489",
          "md5": "56d07c46943c0721f406cd321bd398d6"
        }
      ]
    }
  ]
}
