{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-9aa7816315095c86410527932918c718cb35e7d6"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_debug-1.0.aar",
          "url": "sqflite_debug-1.0.aar",
          "size": 46827,
          "sha512": "87d33db7ea4559f6d1ebdfb05962e8c09fdeadc528cbc83a2178f94a125b452ce25528a242690384e2d74070a4b770f4df7f46a59c9601e5d7fcd3ddb6cd52cb",
          "sha256": "fc852bbd89885618228af526b7270fa3a8ab19814e2e522353b95ee005bb6a12",
          "sha1": "9602622a7f912afb7328dad53c5f87fc4d6e35b8",
          "md5": "2cee42f2202f6ff5c0795c76c9baf5d8"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-9aa7816315095c86410527932918c718cb35e7d6"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_debug-1.0.aar",
          "url": "sqflite_debug-1.0.aar",
          "size": 46827,
          "sha512": "87d33db7ea4559f6d1ebdfb05962e8c09fdeadc528cbc83a2178f94a125b452ce25528a242690384e2d74070a4b770f4df7f46a59c9601e5d7fcd3ddb6cd52cb",
          "sha256": "fc852bbd89885618228af526b7270fa3a8ab19814e2e522353b95ee005bb6a12",
          "sha1": "9602622a7f912afb7328dad53c5f87fc4d6e35b8",
          "md5": "2cee42f2202f6ff5c0795c76c9baf5d8"
        }
      ]
    }
  ]
}
