{
  "formatVersion": "1.1",
  "component": {
    "group": "com.crazecoder.openfile",
    "module": "open_filex_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-9aa7816315095c86410527932918c718cb35e7d6"
          }
        }
      ],
      "files": [
        {
          "name": "open_filex_release-1.0.aar",
          "url": "open_filex_release-1.0.aar",
          "size": 13624,
          "sha512": "5842e414bd2ab5a4333d8e4d2ffc0e0628aa6995b9d5a5fc012a3747fd714d5e54d5b8acf31f376a49a3066476b9a74c4a0c7d1dfcf96bb6e07065ceb1d233d2",
          "sha256": "6b42c21c0166c98c17a4ea2f6fa4196a5b83973698abec9466e516e100b03f4f",
          "sha1": "6ddbf7d02942c200c5ca294609ee88bbcd324c0a",
          "md5": "54db00775939564e11e7fb6a7b530a48"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-9aa7816315095c86410527932918c718cb35e7d6"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "open_filex_release-1.0.aar",
          "url": "open_filex_release-1.0.aar",
          "size": 13624,
          "sha512": "5842e414bd2ab5a4333d8e4d2ffc0e0628aa6995b9d5a5fc012a3747fd714d5e54d5b8acf31f376a49a3066476b9a74c4a0c7d1dfcf96bb6e07065ceb1d233d2",
          "sha256": "6b42c21c0166c98c17a4ea2f6fa4196a5b83973698abec9466e516e100b03f4f",
          "sha1": "6ddbf7d02942c200c5ca294609ee88bbcd324c0a",
          "md5": "54db00775939564e11e7fb6a7b530a48"
        }
      ]
    }
  ]
}
