{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jrai.flutter_keyboard_visibility",
    "module": "flutter_keyboard_visibility",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_keyboard_visibility-1.0-debug.aar",
          "url": "flutter_keyboard_visibility-1.0-debug.aar",
          "size": 5055,
          "sha512": "3f711d7484394bd35804f4a9eebb828e5e7cf03dfc62a6752241b70131a9a79f0707e0194cba54652a68c1d0e47c965a0e29adba8884c93ff3ef9417aaced38b",
          "sha256": "6599c86efd97934e664ffb48010f810d95a6aa0101a4ccb43c7de9f2906aae3a",
          "sha1": "ceacb73190a69bb558467ce9edc51785ca827bf8",
          "md5": "8324d24960e93c71ce16e5d9f9e27436"
        }
      ]
    },
    {
      "name": "debugVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_keyboard_visibility-1.0-debug.aar",
          "url": "flutter_keyboard_visibility-1.0-debug.aar",
          "size": 5055,
          "sha512": "3f711d7484394bd35804f4a9eebb828e5e7cf03dfc62a6752241b70131a9a79f0707e0194cba54652a68c1d0e47c965a0e29adba8884c93ff3ef9417aaced38b",
          "sha256": "6599c86efd97934e664ffb48010f810d95a6aa0101a4ccb43c7de9f2906aae3a",
          "sha1": "ceacb73190a69bb558467ce9edc51785ca827bf8",
          "md5": "8324d24960e93c71ce16e5d9f9e27436"
        }
      ]
    },
    {
      "name": "releaseVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_keyboard_visibility-1.0-release.aar",
          "url": "flutter_keyboard_visibility-1.0-release.aar",
          "size": 4830,
          "sha512": "18382ca165fd4e95709f2ba49e3d3aeba05fedae5da485d733149285d2ad95b6c811ee79581e92a3490f4c9b972017b47187391abb450c61e08e6e406f9fc531",
          "sha256": "6f31324d80f05245a99835e375492d67db1e620fc91bab37df4352cdf88be693",
          "sha1": "4e781ea963e6110a17c107868648b64dae7f966c",
          "md5": "a54d670f54df67851232e6f55d387919"
        }
      ]
    },
    {
      "name": "releaseVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_keyboard_visibility-1.0-release.aar",
          "url": "flutter_keyboard_visibility-1.0-release.aar",
          "size": 4830,
          "sha512": "18382ca165fd4e95709f2ba49e3d3aeba05fedae5da485d733149285d2ad95b6c811ee79581e92a3490f4c9b972017b47187391abb450c61e08e6e406f9fc531",
          "sha256": "6f31324d80f05245a99835e375492d67db1e620fc91bab37df4352cdf88be693",
          "sha1": "4e781ea963e6110a17c107868648b64dae7f966c",
          "md5": "a54d670f54df67851232e6f55d387919"
        }
      ]
    },
    {
      "name": "profileVariantAllApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_keyboard_visibility-1.0-profile.aar",
          "url": "flutter_keyboard_visibility-1.0-profile.aar",
          "size": 4825,
          "sha512": "765d6fba88e17465c70999ef2dfb1fd4a603ca1595e0c8f9f4af969aa4383b6f28b2e10b6dd239a5cc2614f6f7589ad56adfd917cc48c3434225ed0ed91884e6",
          "sha256": "aacdbb88c9e5e43d48fc3102926ea65a2931a43c4ea8f59b155b79e6a1069b79",
          "sha1": "236bdd3426f61a8b97317503aef5ad44b6fed483",
          "md5": "780b958d399c65b409557af37aca1f1d"
        }
      ]
    },
    {
      "name": "profileVariantAllRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "profile",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_keyboard_visibility-1.0-profile.aar",
          "url": "flutter_keyboard_visibility-1.0-profile.aar",
          "size": 4825,
          "sha512": "765d6fba88e17465c70999ef2dfb1fd4a603ca1595e0c8f9f4af969aa4383b6f28b2e10b6dd239a5cc2614f6f7589ad56adfd917cc48c3434225ed0ed91884e6",
          "sha256": "aacdbb88c9e5e43d48fc3102926ea65a2931a43c4ea8f59b155b79e6a1069b79",
          "sha1": "236bdd3426f61a8b97317503aef5ad44b6fed483",
          "md5": "780b958d399c65b409557af37aca1f1d"
        }
      ]
    }
  ]
}
