{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ryanheise.just_audio",
    "module": "just_audio_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "just_audio_debug-1.0.aar",
          "url": "just_audio_debug-1.0.aar",
          "size": 29790,
          "sha512": "41fd3bcec3219952c0b80f7e5fe8af60f36e37a7df7e848540825dae19ed787d83f77aab8d016c0a11f903622a00ebab6088d03c8133dda090a51dfa0fad3529",
          "sha256": "f920e69bd81adaffbd60e6b0f465fd6081ca9347c5de4ab95974d69fcfc2c11d",
          "sha1": "0fb709584f8c2216c42e335e5c0dd251b67f24e0",
          "md5": "6d66ac35b23510393c8d3e486a8c59c1"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-smoothstreaming",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "just_audio_debug-1.0.aar",
          "url": "just_audio_debug-1.0.aar",
          "size": 29790,
          "sha512": "41fd3bcec3219952c0b80f7e5fe8af60f36e37a7df7e848540825dae19ed787d83f77aab8d016c0a11f903622a00ebab6088d03c8133dda090a51dfa0fad3529",
          "sha256": "f920e69bd81adaffbd60e6b0f465fd6081ca9347c5de4ab95974d69fcfc2c11d",
          "sha1": "0fb709584f8c2216c42e335e5c0dd251b67f24e0",
          "md5": "6d66ac35b23510393c8d3e486a8c59c1"
        }
      ]
    }
  ]
}
