{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ryanheise.just_audio",
    "module": "just_audio_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        }
      ],
      "files": [
        {
          "name": "just_audio_release-1.0.aar",
          "url": "just_audio_release-1.0.aar",
          "size": 28013,
          "sha512": "eacc1e829faa561bf0115765fca3f6e610fe8d28766526f953ab4c00adaa7ef6a8f5a46957a1bf023d759a26f74870fc503468edcbe221d2c1e6ba3da92c1897",
          "sha256": "4949c988d3226a1dd7a1f253c72adbd19736b323b7d6b3d10eeaad25dfd5338f",
          "sha1": "c2c1e5c54d870d72a326ec5b41fa78ad458df4d4",
          "md5": "adab27ae1b002568a8192f11a20b2e6d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-8f2221fbef28b478debb78dd233f5250b220ca99"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-smoothstreaming",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "just_audio_release-1.0.aar",
          "url": "just_audio_release-1.0.aar",
          "size": 28013,
          "sha512": "eacc1e829faa561bf0115765fca3f6e610fe8d28766526f953ab4c00adaa7ef6a8f5a46957a1bf023d759a26f74870fc503468edcbe221d2c1e6ba3da92c1897",
          "sha256": "4949c988d3226a1dd7a1f253c72adbd19736b323b7d6b3d10eeaad25dfd5338f",
          "sha1": "c2c1e5c54d870d72a326ec5b41fa78ad458df4d4",
          "md5": "adab27ae1b002568a8192f11a20b2e6d"
        }
      ]
    }
  ]
}
