{
  "formatVersion": "1.1",
  "component": {
    "group": "com.crazecoder.openfile",
    "module": "open_filex_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-9aa7816315095c86410527932918c718cb35e7d6"
          }
        }
      ],
      "files": [
        {
          "name": "open_filex_debug-1.0.aar",
          "url": "open_filex_debug-1.0.aar",
          "size": 14162,
          "sha512": "64b06b88ee4a3e775d85991f1156676f5dfd67dde8560dac767bb2793ec09746a103405ea5c9f503a3f5144436ac8caaa06b1a2da8ee5e8b82f41b8b7d8b7a25",
          "sha256": "9fba0cbc409aea7db0992093544481ab9be5a834b1c6e262628dab6286036783",
          "sha1": "48bd3372a2c6cede8dd112c40cabfd3bf9f33e0e",
          "md5": "89af8825de905c27737a6ad95ed331fd"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-9aa7816315095c86410527932918c718cb35e7d6"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "open_filex_debug-1.0.aar",
          "url": "open_filex_debug-1.0.aar",
          "size": 14162,
          "sha512": "64b06b88ee4a3e775d85991f1156676f5dfd67dde8560dac767bb2793ec09746a103405ea5c9f503a3f5144436ac8caaa06b1a2da8ee5e8b82f41b8b7d8b7a25",
          "sha256": "9fba0cbc409aea7db0992093544481ab9be5a834b1c6e262628dab6286036783",
          "sha1": "48bd3372a2c6cede8dd112c40cabfd3bf9f33e0e",
          "md5": "89af8825de905c27737a6ad95ed331fd"
        }
      ]
    }
  ]
}
